import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import openapiTS, { astToString } from "openapi-typescript";

// There is deliberately no default: the spec is named on every run so the
// types can never be regenerated from the wrong one by accident.
const SOURCE_HELP =
  "Pass the spec as an argument or set LAYLO_OPENAPI_SOURCE, e.g. " +
  "npm run generate -- ./openapi.json";
const BANNER = "// Generated by scripts/generate-types.ts — do not edit\n";

const outputPath = fileURLToPath(
  new URL("../src/generated/openapi.ts", import.meta.url),
);

const toSpecUrl = (specSource: string) => {
  if (/^https?:\/\//.test(specSource)) {
    return new URL(specSource);
  }

  return pathToFileURL(resolve(specSource));
};

const readCommitted = async () => {
  try {
    return await readFile(outputPath, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return null;
    }

    throw error;
  }
};

const run = async () => {
  const cliArguments = process.argv.slice(2);
  const unknownOptions = cliArguments.filter(
    (argument) => argument.startsWith("--") && argument !== "--check",
  );
  if (unknownOptions.length > 0) {
    console.error(`Unknown option: ${unknownOptions.join(" ")}`);
    return 1;
  }

  const checkOnly = cliArguments.includes("--check");
  const sourceArgument = cliArguments.find(
    (argument) => argument !== "--check",
  );
  const source = sourceArgument ?? process.env.LAYLO_OPENAPI_SOURCE;
  if (!source) {
    console.error(`No OpenAPI spec source given. ${SOURCE_HELP}`);
    return 1;
  }

  const ast = await openapiTS(toSpecUrl(source), {
    alphabetize: true,
    enum: false,
    exportType: true,
  });
  const generated = BANNER + astToString(ast);

  if (checkOnly) {
    const committed = await readCommitted();
    if (committed !== generated) {
      console.error(
        `src/generated/openapi.ts is out of date with ${source}; run npm run generate`,
      );
      return 1;
    }

    console.log(`src/generated/openapi.ts matches ${source}`);
    return 0;
  }

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, generated);
  console.log(`Wrote src/generated/openapi.ts from ${source}`);
  return 0;
};

process.exitCode = await run();
